### PR TITLE
fix GPIO number mappings for DragonBoard410c

### PR DESCRIPTION
**Pull request by t-higuchi**
on DragonBoard410c, GPIO-F is connected to MPP4 pin of PMIC chip (PM8916)
instead of main SoC.

### CODE REVIEW

**Comment by jackmitch** [comment]
Which kernel does this apply to? Is it one set of numbers for the vendor kernel and a second set for mainline?

**Comment by t-higuchi** [comment]
Thanks for your quick response.


I have tested this patch with kernel for official Linux releases for DragonBoard410c:
   
  https://builds.96boards.org/releases/dragonboard410c/linaro/debian/16.09   (latest version, linux-4.4.23)
  https://builds.96boards.org/releases/dragonboard410c/linaro/debian/16.06   (linux-4.4.9)

Both set of numbers applies to the same kernel.
First set (GPIO-{A-F} = nnn) maps signal names on schematics (and 96boards CE specification) to GPIO numbers,
and second set maps pin numbers of board-to-board connector to GPIO numbers.

**Comment by fboudra** [comment]
@jackmitch I asked @ndechesne to look at this pull request and confirm it's correct.

**Comment by ndechesne** [comment]
I agree that as it is currently done, it is wrong. GPIO_F is mapped to MPP4 GPIO, so offset '4' 

MPPS are GPIOs from the PMIC, not from the SOC. So they are controlled by a different controller:

```
root@dragonboard-410c:/sys/kernel/debug/pinctrl# cat */gpio-ranges
GPIO ranges handled:
0: 1000000.pinctrl GPIOS [0 - 121] PINS [0 - 121]
GPIO ranges handled:
0: 200f000.spmi:pm8916@0:gpios@c000 GPIOS [508 - 511] PINS [0 - 3]
GPIO ranges handled:
0: 200f000.spmi:pm8916@0:mpps@a000 GPIOS [504 - 507] PINS [0 - 3]
```

This is with any recent/mainline kernel. However I am not sure where the initial 504 offset is coming from, and what can cause this offset to change..

**Pull request merged**
