### PR TITLE
Update bubblegum.conf

### PR DESCRIPTION
**Pull request by blimjoe**
update the SoC number

### CODE REVIEW

**Comment by jackmitch** [comment]
How come this has changed? Will there be issues with backwards compatibility? I assume the kernel that has the previous pin numbering is still in use somewhere?

**Comment by blimjoe** [comment]
But it seems your bubblegum.conf is not working. We've got the pin number from Actions Hardware Manual and command `dmesg`. Hardware Manual [https://github.com/96boards/documentation/raw/master/bubblegum-96/HardwareManual_Bubblegum96.pdf](url)

**Comment by jackmitch** [comment]
Which kernel are you using on your device?

**Comment by blimjoe** [comment]
3.10.52-linaro-bubblegum
[https://github.com/96boards-bubblegum/linux](url)

**Comment by jackmitch** [comment]
I've pinged a guy I know at Linaro who commited the original config file, see what input he has to offer.

**Comment by doanac** [comment]
ucrobotics has confirmed this change works on their board. +1 on merging.

**Pull request merged**
