### PR TITLE
RFC: Build up support for easier access to GPIOs

### PR DESCRIPTION
**Pull request by doanac**
Hey Jack,

My name is Andy Doan and I work for David Mandala at Linaro. I believe he approached you with regards to making this library a little easier to use for our 96Boards project. The main issue we have is that all the boards have the same GPIO pin layouts (we call GPIO_A ... GPIO_L). However, the actual GPIO ID is different depending on the SoC. As I read your gpio_test.c file, I see that current projects like BeagleBone have similar issues (just not quite as bad). I've tried to come up with a simple, optional (autoconf enabled) solution to this problem.

I was hoping to see what you thought about these patches. The branch is pretty easy to test. Just do something like:

 ./configure BOARD=beaglebone

I attempted to create a beaglebone gpio.conf to make your testing easier. You could then get GPIO id for P9_42 in something like your gpio_test.c file with: libsoc_gpio_id("P9_42")

### CODE REVIEW

**Comment by davidvg** [comment]
Hi, I think you have sent this message to the wrong person :)
The point is I am actually starting working with BeagleBone and last month
I visited your repo in GitHub. Nice work, by the way.

Best regards,
David Vazquez.

2015-10-06 3:43 GMT+02:00 Andy Doan <notifications@github.com>:

**Comment by doanac** [comment]
Hey David - Maybe I'm a little confused. I thought this pull request was
going to Jack Mitchell's libsoc library? I think this change could make
sense for this project, no?

**Comment by davidvg** [comment]
My fault, I read it too fast and thought you had sent me an email; it was a
github notification.
Please feel free to remove my answers and sorry for the inconveniences.

**Comment by jackmitch** [comment]
Hi Andy,

I haven't forgotten about this, still mulling it over!

Cheers,
Jack.

**Comment by jackmitch** [comment]
Hi Andy,

My initial thoughts on how to implement this were a bit wrong I think. I had the idea that the GPIO mappings would be built into the library on compile time, but I now see a few issues with that, e.g. board-specific library (i.e. can't have a single library build for an architecture with board support enabled). I have a few style niggles with the code to which I'll add some comments in-line then I think I'll be happy to take this as an initial implementation and give it a public showing with a view that it could still be re-worked.

**Comment by doanac** [comment]
Hey Jack,

I just did a "git push -f" on this branch to upload my v2 of this patchset. Main changes are:

* added a new commit for a libsoc_warn api
* board_test.c uses plain linux file descriptors
* initialization is no longer "automagic". Users must call libsoc_board_init and optionally libsoc_board_free
* documented headers

**Comment by doanac** [comment]
I just did a "push -f" for v3. The only commit that changed was the the for the libsoc_board_* stuff. It includes:
 * update of name from libsoc_gpio_id -> libsoc_board_gpio_id
 * board_test.c includes number of failures in output
 * board.[ch] are now always compiled/installed.
 * whitespace fixes

**Comment by jackmitch** [comment]
Ok, looks almost there; I have created a patch to change the configure method, so rather than BOARD=x ./configure we have ./configure --enable-board=x

https://github.com/jackmitch/libsoc/commit/c6a0c758bbc2e57775c1d14ababa2c3177f943cc

If you just squash that into your patch it should be fine.

Finally, could you add an update to the readme, with the new option for the front page.

**Comment by doanac** [comment]
Okay - I think this patchset is ready. Its added a new commit on the tip for the README change and updated the ./configure usage.

**Comment by jackmitch** [comment]
Looks good to me, thanks for the co-operation Andy, I know I was a bit nit picky!

**Comment by doanac** [comment]
Thanks Jack. As a maintainer, any patch you accept adds some level of
potential technical debt, so I respect your attention to detail to get this
done right.

**Pull request merged**
