### PR TITLE
config: rpi3: add config file

### PR DESCRIPTION
**Pull request by bhuvanchandra**
Raspberry Pi 3 config file. libsoc examples [here.](https://github.com/bhuvanchandra/libsoc-examples/tree/rpi3)

### CODE REVIEW

**Comment by jackmitch** [comment]
Thanks for the pull request, do you know how many revisions of the Raspberry Pi 3 there are?

For example if the user has a Rev 1, or rev 1.3 then I assume the dt compatible won't match; but how would they then select a configuration to use?

If the other revisions were never publically released then I'll be happy to take this otherwise we should rename it raspberrypi3-rev1.2.conf. If this is the case can you also check the parsing works with additional '.' characters in the name.

**Comment by bhuvanchandra** [comment]
I couldn't find the list of revisions of Raspberry Pi 3's officially. Also the model from the device tree is overwritten somehow.

These are the models I could see in device trees for Rpi models:

> arch/arm/boot/dts/bcm2708-rpi-b-plus.dts:       model = "Raspberry Pi Model B+";
> arch/arm/boot/dts/bcm2708-rpi-b.dts:            model = "Raspberry Pi Model B";
> arch/arm/boot/dts/bcm2708-rpi-cm.dts:           model = "Raspberry Pi Compute Module";
> arch/arm/boot/dts/bcm2709-rpi-2-b.dts:          model = "Raspberry Pi 2 Model B";
> arch/arm/boot/dts/bcm2835-rpi-b-plus.dts:       model = "Raspberry Pi Model B+";
> arch/arm/boot/dts/bcm2835-rpi-b.dts:            model = "Raspberry Pi Model B";
> arch/arm/boot/dts/bcm2710-rpi-3-b.dts          model = "Raspberry Pi 3 Model B";
> arch/arm/boot/dts/bcm2710-rpi-3-b-plus.dts   model = "Raspberry Pi 3 Model B+";
> ...

But the revision is getting appended/overwritten from the /boot/start_*.elf binary I guess.

I will look deep into the available/possible versions of Rpi3.
IMHO in b/w the h/w revisions the GPIO mapping will/could remain same. If this is true we would end up maintaining redundent config files per device-tree model.
What do you think ?

**Comment by bhuvanchandra** [comment]
Found one reference in Raspberry PI documentation [here.](https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md)

There are officially two revisions for Rpi 3(v1.2 and v1.3). I agree with your earlier comment on adding new config file per revision. 

>> If the other revisions were never publicly released then I'll be happy to take this otherwise we should rename it raspberrypi3-rev1.2.conf. If this is the case can you also check the parsing works with additional '.' characters in the name.

Instead of using version name as '1.2' we can use it as '1v2'

e.g.:
> raspberrypi3-rev1v2.conf
> raspberrypi3-rev1v3.conf

**Comment by jackmitch** [comment]
Thanks!

**Pull request merged**
