### PR TITLE
Small fixups

### PR DESCRIPTION
**Pull request by doanac**
Fixes two small issues I noticed today

### CODE REVIEW

**Comment by jackmitch** [comment]
What are your thoughts in general on the python functions, should people be using the api directly like in the tests or should we be wrapping them in the class? I ask due to #49

**Comment by ukBaz** [comment]
I'm not sure if it helps the discussions but here is a link to what I'm creating as a workshop around GPIO using libsoc:
http://pythonhosted.org/libsoc_zero/experiments.html

This uses a python module that I've created at:
https://github.com/DBOpenSource/linker_starter_kit/tree/master/libsoc_zero

And can be installed with 'pip3 install libsoc_zero' because it is hosted at:
https://pypi.python.org/pypi/libsoc_zero

Why libsoc_zero?
https://github.com/py-zerozero/zerozero

**Comment by doanac** [comment]
I treat "api" as internal. We should just have a set_edge API on the GPIO. I think I originally did that, but thought it could just be managed when the GPIO is constructed. That seems short-sighted now.

Would you like to assign #49 to me and I'll send you a fix?

**Comment by jackmitch** [comment]
Yeah, that would be great. I tried and failed to assign you to the issue. It wouldn't take your username but if you just include the issue number in the commit that should do.

**Pull request merged**
