### PR TITLE
Add optional python 2 or 3 language bindings

### PR DESCRIPTION
**Pull request by doanac**
This is a cleaner redo of:

 https://github.com/jackmitch/libsoc/pull/31

I think it addresses most if all not all of the original concerns. Its been tested with both Python 2.7 and 3.4 on a Dragonboard 410c

### CODE REVIEW

**Comment by jackmitch** [comment]
Thanks Andy, lets give it a whirl and see if any issues shake out.

Cheers!

**Comment by jackmitch** [comment]
HI Andy,

I've had to tweak the python autotools integration again. If you could give it a whirl with your setup to check it hasn't broken anything that would be appreciated!

https://github.com/jackmitch/libsoc/issues/39

Cheers,
Jack.

**Comment by doanac** [comment]
Sorry about that Jack, autotools is still a struggle for me. I pulled in your changes and I can do both cross and native compiles with it.

**Comment by jackmitch** [comment]
No worries; you usually need a full moon and perfect alignment of the runes to get it right first time.

**Pull request merged**
